#-------------------------------
# General Site Settings
baseurl: "" # The subpath of your site, e.g. /blog
url: "" # The base hostname & protocol for your site, e.g. http://example.com

title: OOBr 
logo: /assets/images/logo.png # You can add own logo
description: # Add your awesome description
copyright: Copyright 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com)
# Preloader
preloader: true # To disable preloader change value to false

menu:
  - name: Início
    url: /
  - name: Sobre
    url: /about/
  #- name: Contato
  #  url: /contact/

# *** NOTE ***
# You can add submenus. For example:

#  menu:
#  - name: Home
#    url: /
#    submenu:
#     - name: Peru
#       url: /peru/
# ----------------------------------

layout_home_page: true # Homepage layout ( two layout is available, you can set the another layout by change the value of layout_home_page "true" to "false")

featured-post-slider: true # You can enable or disable the featured-post-slider using true or false values.

#-------------------------------
# Hero Section
hero:
  hero-subtitle: teste
  hero-banner: /assets/images/banner-img.png # Add your banner image '/assets/images/'

#-------------------------------
# Author Settings
author:
  name: OOBr

#-------------------------------
# Contact Info
contact:
  email: observatorioobstetricobr@gmail.com

# Contact Form
contact-form: observatorioobstetricobr@gmail.com

# Social links
social:
- {icon: "ti-twitter-alt", link: "https://twitter.com/observatorioobr"}
- {icon: "ti-youtube", link: "https://www.youtube.com/channel/UCp4k0g_6yP-S8G2DU6_lSeQ"}
- {icon: "ti-instagram", link: "https://www.instagram.com/observatorioobr/"}

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.
userID: 4044026246
accessToken: 4044026246.1677ed0.8896752506ed4402a0519d23b8f50a17

#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.

#-------------------------------
# Build settings
markdown: kramdown
syntax_highlighter: rouge
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-archives

paginate: 10
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# categories
jekyll-archives:
  enabled: all
  layout: category
  permalinks:
    category: '/category/:name/'

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor